models:
  - type: main
    engine: nim
    model: meta/llama-3.3-70b-instruct

rails:
  input:
    flows:
      - jailbreak detection model

  output:
    flows: []

  config:
    jailbreak_detection:
      nim_base_url: "https://ai.api.nvidia.com"
      nim_server_endpoint: "/v1/security/nvidia/nemoguard-jailbreak-detect"
      api_key_env_var: NVIDIA_API_KEY
