# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Ergonomic helper for writing conversational tests against a guardrails config."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Union

from nemoguardrails import LLMRails, RailsConfig
from nemoguardrails.testing.fake_model import FakeLLMModel
from nemoguardrails.utils import new_event_dict, new_uuid

_TEST_PROVIDERS_WITH_TOKEN_USAGE = ["openai", "azure_openai", "nim"]


def _is_data_in_events(events: List[Dict[str, Any]], event_data: List[Dict[str, Any]]) -> bool:
    if len(events) != len(event_data):
        return False

    for event, data in zip(events, event_data, strict=True):
        if not (all(key in event for key in data) and all(data[key] == event[key] for key in data)):
            return False
    return True


class TestChat:
    """Helper class for easily writing tests.

    Usage:
        config = RailsConfig.from_path(...)
        chat = TestChat(
            config,
            llm_completions=[
                "Hello! How can I help you today?",
            ],
        )

        chat.user("Hello! How are you?")
        chat.bot("Hello! How can I help you today?")

    """

    __test__ = False

    def __init__(
        self,
        config: RailsConfig,
        llm_completions: Optional[List[str]] = None,
        streaming: bool = False,
        llm_exception: Optional[Exception] = None,
        token_usage: Optional[List[Dict[str, int]]] = None,
        llm: Optional[FakeLLMModel] = None,
    ):
        """Creates a TestChat instance.

        Args:
            config: The Rails configuration.
            llm_completions: The completions that should be generated by the
                fake LLM. Mutually exclusive with ``llm``.
            streaming: Whether to simulate streaming responses.
            llm_exception: An exception to be raised by the LLM (for testing
                error handling).
            token_usage: Optional token usage data for simulating token usage
                reporting.
            llm: An explicit LLM instance to bind to the rails app. When
                provided, ``llm_completions`` is ignored.
        """
        if llm is not None:
            self.llm = llm
        elif llm_completions is not None or llm_exception is not None:
            main_model = next((model for model in config.models if model.type == "main"), None)
            should_return_token_usage = bool(main_model and main_model.engine in _TEST_PROVIDERS_WITH_TOKEN_USAGE)

            self.llm = FakeLLMModel(
                responses=llm_completions,
                llm_exception=llm_exception,
                token_usage=token_usage,
                should_return_token_usage=should_return_token_usage,
            )
        else:
            self.llm = None

        self.config = config
        self.app = LLMRails(config, llm=self.llm)

        self.history = []
        self.streaming = streaming

        self.input_events = []
        self.state = None

        if self.config.colang_version == "2.x":
            self.app.runtime.disable_async_execution = True
            _, self.state = self.app.process_events(
                [],
                self.state,
            )

    def user(self, msg: Union[str, dict]):
        if self.config.colang_version == "1.0":
            self.history.append({"role": "user", "content": msg})
        elif self.config.colang_version == "2.x":
            if isinstance(msg, str):
                action_uid = new_uuid()
                self.input_events.extend(
                    [
                        new_event_dict("UtteranceUserActionStarted", action_uid=action_uid),
                        new_event_dict(
                            "UtteranceUserActionFinished",
                            final_transcript=msg,
                            action_uid=action_uid,
                            is_success=True,
                            event_created_at=(datetime.now(timezone.utc) + timedelta(milliseconds=1)).isoformat(),
                            action_finished_at=(datetime.now(timezone.utc) + timedelta(milliseconds=1)).isoformat(),
                        ),
                    ]
                )
            elif "type" in msg:
                self.input_events.append(msg)
            else:
                raise ValueError(f"Invalid user message: {msg}. Must be either str or event")
        else:
            raise Exception(f"Invalid colang version: {self.config.colang_version}")

    def bot(self, expected: Union[str, dict, list]):
        if self.config.colang_version == "1.0":
            result = self.app.generate(messages=self.history)
            assert result, "Did not receive any result"
            assert result["content"] == expected, f"Expected `{expected}` and received `{result['content']}`"
            self.history.append(result)

        elif self.config.colang_version == "2.x":
            output_msgs = []
            output_events = []
            while self.input_events:
                event = self.input_events.pop(0)
                out_events, output_state = self.app.process_events([event], self.state)
                output_events.extend(out_events)

                for event in out_events:
                    if event["type"] == "StartUtteranceBotAction":
                        output_msgs.append(event["script"])
                        self.input_events.append(
                            new_event_dict(
                                "UtteranceBotActionStarted",
                                action_uid=event["action_uid"],
                            )
                        )
                        self.input_events.append(
                            new_event_dict(
                                "UtteranceBotActionStarted",
                                action_uid=event["action_uid"],
                            )
                        )
                        self.input_events.append(
                            new_event_dict(
                                "UtteranceBotActionFinished",
                                action_uid=event["action_uid"],
                                is_success=True,
                                final_script=event["script"],
                            )
                        )

                self.state = output_state

            output_msg = "\n".join(output_msgs)
            if isinstance(expected, str):
                assert output_msg == expected, f"Expected `{expected}` and received `{output_msg}`"
            else:
                if isinstance(expected, dict):
                    expected = [expected]
                assert _is_data_in_events(output_events, expected)

        else:
            raise Exception(f"Invalid colang version: {self.config.colang_version}")

    async def bot_async(self, msg: str):
        result = await self.app.generate_async(messages=self.history)
        assert result, "Did not receive any result"
        assert result["content"] == msg, f"Expected `{msg}` and received `{result['content']}`"
        self.history.append(result)

    def __rshift__(self, msg: Union[str, dict]):
        self.user(msg)

    def __lshift__(self, msg: str):
        self.bot(msg)
