name: Close stale issues and PRs

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          any-of-issue-labels: "status: needs info,status: waiting confirmation"
          days-before-issue-stale: 14
          days-before-issue-close: 7
          stale-issue-label: "status: stale"
          stale-issue-message: "This issue is stale because it has been open with no activity. It will be closed in 7 days if no further activity occurs."
          close-issue-message: "Closing this issue as it has been inactive. Please reopen if it is still relevant."

          any-of-pr-labels: "status: needs info"
          days-before-pr-stale: 21
          days-before-pr-close: 7
          stale-pr-label: "status: stale"
          stale-pr-message: "This PR is stale because it has been open with no activity. It will be closed in 7 days if no further activity occurs."
          close-pr-message: "Closing this PR as it has been inactive. Please reopen if you intend to continue."
